services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        volumes:
            - .:/var/www/html
        depends_on:
            - db
            - redis
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        container_name: nginx-webserver
        ports:
            - "3000:80"
        volumes:
            - .:/var/www/html
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - app-network

    db:
        image: postgres:13
        container_name: postgres-db
        environment:
            POSTGRES_DB: inventory_system_database
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1337
        ports:
            - "5433:5432"
        volumes:
            - dbdata:/var/lib/postgresql/data
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: redis-cache
        ports:
            - "6379:6379"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
